dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: src/app
  on:
    branch: master

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

script:
  - npm run test-single-run -- --browsers ChromeHeadless
